### ISSUE TITLE
Update docs toolstack in READ.md

### ISSUE THREAD

**Issue by daveatweaviate** [weaviate/weaviate-io#1093]
### Code of Conduct

- [X] I have read and agree to the Weaviate's [Code of Conduct](https://github.com/weaviate/weaviate-io/blob/main/CODE_OF_CONDUCT.md)

### What part of document/web-page on weaviate.io is affected?

The docstack installation instructions in the README.md need more detail.

**Comment by daveatweaviate** [comment]
[PR](https://github.com/weaviate/weaviate-io/pull/1094)

**Comment by databyjp** [comment]
Merged :)
