### ISSUE TITLE
Add cURL cross reference example

### ISSUE THREAD

**Issue by daveatweaviate** [weaviate/weaviate-io#1117]
### What part of document/web-page on weaviate.io is affected?

There is a cURL example [here](https://weaviate.io/developers/weaviate/api/rest/objects#cross-references). 
There should be one [here](https://weaviate.io/developers/weaviate/manage-data/cross-references#retrieve-crossreferences) as well.

Sample to add a reference

```
curl \
    -X POST \
    -H "Content-Type: application/json" \
    -d '{"beacon": "weaviate://localhost/<REFERENCED_CLASS_NAME>/<REFERENCED_OBJECT_UUID>" }' \
    https://<WEAVIATE_URI>/v1/objects/<REFERENCING_CLASS_NAME>/<REFERENCING_OBJECT_UUID>/references/<REFERENCED_CLASS_PROPERY>?consistency_level=ALL[,tenant=<TENANT_ID>]

Lets say you have class A with property toB, another class B that A will reference, and no Multi tenancy enabled. The curl will look like this:

curl \
    -X POST \
    -H "Content-Type: application/json" \
    -d '{"beacon": "weaviate://localhost/B/<B_OBJECT_UUID>" }' \
    https://<WEAVIATE_URI>/v1/objects/A/<A_OBJECT_UUID>/references/toB?consistency_level=ALL
```

[slack](https://weaviate-org.slack.com/archives/C04LB3DLSSG/p1694679565914979)

**Comment by ankur0904** [comment]
@daveatweaviate  I want to work on this issue.

**Comment by daveatweaviate** [comment]
Hi @ankur0904, thanks for your interest in Weaviate! Welcome!

If you haven't done so already, please have a look at the [Contributor Guide](https://weaviate.io/developers/contributor-guide) and the [README](https://github.com/weaviate/weaviate-io/blob/main/README.md) page for docs contributions.

When you are ready to submit your update, open a pull request (PR) in this project for us to review.

Thanks again, 

Dave

**Comment by ankur0904** [comment]
Thank you too @daveatweaviate.

**Comment by daveatweaviate** [comment]
Closing - we don't plan to add cURL examples in this section of the docs.
