### ISSUE TITLE
Inconsistency in the `scripts` in `README.md` file

### ISSUE THREAD

**Issue by ankur0904** [weaviate/weaviate-io#1121]
### Code of Conduct

- [X] I have read and agree to the Weaviate's [Code of Conduct](https://github.com/weaviate/weaviate-io/blob/main/CODE_OF_CONDUCT.md)

### What part of document/web-page on weaviate.io is affected?

In https://github.com/weaviate/weaviate-io/blob/main/README.md some places `$` sign is present before the `script` and someplaces sign in not present.

**E.g.:**
```
$ yarn start &
```
and
```
nvm use node 19.9.0
```

**Comment by databyjp** [comment]
If I'm not mistaken, I think it's been removed in a [parallel PR](https://github.com/weaviate/weaviate-io/pull/1113) :)

**Comment by ankur0904** [comment]
@databyjp Great.
