### ISSUE TITLE
Copy to clipboard button also copies $ symbol

### ISSUE THREAD

**Issue by lalit-k** [weaviate/weaviate-io#1200]
### Code of Conduct

- [X] I have read and agree to the Weaviate's [Code of Conduct](https://github.com/weaviate/weaviate-io/blob/main/CODE_OF_CONDUCT.md)

### Steps to reproduce the bug

1. Go to page https://weaviate.io/developers/weaviate/client-libraries/python
2. Scroll to first command example which tells how to install weaviate-client i.e "$ pip install weaviate-client"
3. Click the copy icon to copy command.
4. Paste it in your terminal and press Enter

Actual:
Note the commands fails to run, as it have prefixed $ symbol.

### Expected behavior

Commands examples should not start with $.

Note: This is just one example, issue is reproducible on other pages too.

### Screenshots

<img width="967" alt="Screenshot 2023-10-08 at 17 17 38" src="https://github.com/weaviate/weaviate-io/assets/4278995/fc3eb1d2-c4cf-43df-98dd-82def5912966">

**Comment by lalit-k** [comment]
I'd like to work on a fix for this issue. thanks!

**Comment by databyjp** [comment]
Hi @lalit-k - thanks for pointing this out. Please feel free to remove the extra `$` from the doc examples where you see them and we will review any PRs. Thanks! 🙏
