### ISSUE TITLE
GitHub Tab 

### ISSUE THREAD

**Issue by Ayush9026** [weaviate/weaviate-io#1209]
### Code of Conduct

- [X] I have read and agree to the Weaviate's [Code of Conduct](https://github.com/weaviate/weaviate-io/blob/main/CODE_OF_CONDUCT.md)

### What part of document/web-page on weaviate.io is affected?

When clicking on the "GitHub" tab on the Weaviate website, it appears that the link directs users to the Weaviate Twitter account rather than the intended GitHub repository. This issue hinders the ability for individuals who wish to contribute or engage with Weaviate on GitHub to readily access the platform. In the screenshot tab is marked .
![weaviate front page](https://github.com/weaviate/weaviate-io/assets/114745463/f7fb0b9c-2226-4490-b582-b06718e7cbbc)

**Comment by Shan-Weaviate** [comment]
Hi @Ayush9026 

Hope you are well. 

Thanks for the find! 
This has been updated and the fix is live. There is now only one link with correct URL to GH. 

Thanks
Shan
