### ISSUE TITLE
[Documentation Feedback]: "Standalone or modules" step no longer present in cluster creation?

### ISSUE THREAD

**Issue by dandv** [weaviate/weaviate-io#219]
### Page URL

https://weaviate.io/developers/weaviate/current/getting-started/installation.html#create-a-weaviate-cluster

### User feedback

In the "Create a Weaviate Cluster" instructions on the page, step 2.4 is "Leave the Standalone Or Modules as Standalone, no Modules". That steps is missing from the Console:

![image](https://user-images.githubusercontent.com/33569/194012995-76a15b46-0cef-49d2-8bb2-f22abf4e7feb.png)

**Comment by bobvanluijt** [comment]
Hi @dandv – thanks for creating the issue.

Currently, the modules for [OpenAI](https://weaviate.io/developers/weaviate/current/retriever-vectorizer-modules/text2vec-openai.html) and [Huggingface](https://weaviate.io/developers/weaviate/current/retriever-vectorizer-modules/text2vec-huggingface.html) are enabled by default. 

Is that helpful?

**Comment by databyjp** [comment]
Hey @dandv - I have updated this in #386 - will close this issue. Thanks!
