### ISSUE TITLE
[Documentation Feedback]: Wikipedia search demos fail in Firefox due to HTTPS-only mode

### ISSUE THREAD

**Issue by dandv** [weaviate/weaviate-io#222]
### Page URL

https://weaviate.io/developers/weaviate/current/getting-started/query.html

### User feedback

Firefox has [HTTPS-only mode](https://support.mozilla.org/en-US/kb/https-only-prefs) enabled by default. This causes query examples like https://link.semi.technology/3vEV5dD to fail with "NetworkError when attempting to fetch resource."

![image](https://user-images.githubusercontent.com/33569/194202910-2a83e46f-b693-4e9c-985e-bba77a192011.png)

Disabling HTTPS-only works around this issue. Would help to remove this point of friction for Firefox users who may not realize what's going on.

**Comment by databyjp** [comment]
Page has been updated since; closing.
