### ISSUE TITLE
[Documentation Feedback]: Duplicate `distance` and `certainty` variables for nearText?

### ISSUE THREAD

**Issue by dandv** [weaviate/weaviate-io#224]
### Page URL

https://weaviate.io/developers/weaviate/current/graphql-references/vector-search-parameters.html#neartext

### User feedback

![image](https://user-images.githubusercontent.com/33569/194276809-6dfaed2b-b53c-4437-903c-345b46291dd6.png)

**Comment by indrasn0wal** [comment]
assign this issue to me

**Comment by databyjp** [comment]
I think this is fixed. (See #336.) Closing for now.
