### ISSUE TITLE
UX: Texts on the customers section of the homepage is unclear sometimes

### ISSUE THREAD

**Issue by kavirajk** [weaviate/weaviate-io#2438]
### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

### What part of document/web-page on weaviate.io is affected?

Customer section, where different "users" of Weaviate provide feedback. Please find the screenshot below.

NOTE: For example, There is a text after "red-hat" log, but invisible because of the choice of text color and background color.

![Screenshot 2024-08-06 at 10 05 07](https://github.com/user-attachments/assets/5e03c408-f2d3-4f43-a1c8-02af0e7eca19)

### Additional comments?

![Screenshot 2024-08-09 at 15 44 43](https://github.com/user-attachments/assets/508c9efa-7d44-4c67-ab76-2bdd5e8cde77)

More examples (NOTE: there are text beneath David wood and Darpen Patel)

_No response_

**Comment by Shan-Weaviate** [comment]
Hi @kavirajk 

Thanks for the find! 

I will update with some interim changes before the new design is published to accommodate for the styling issues. 

Cheers
Shan
