### ISSUE TITLE
Doc issue: Incorrect sample query link on modules doc

### ISSUE THREAD

**Issue by samos123** [weaviate/weaviate-io#247]
Under Readers & Generators section here: https://weaviate.io/developers/weaviate/current/getting-started/modules.html#readers--generators

It says "You can try this query in real time [here](https://link.semi.technology/3dPI0rV)."

The "here" links to https://link.semi.technology/3dPI0rV which seems to be an incorrect query

**Comment by databyjp** [comment]
Thanks @samos123 and @trengrj 🙏

It looks like the ampersand (`&`) in the GraphQL broke the link. It's been addressed now, with the link updated to (https://link.weaviate.io/3HGe3qv).
