### ISSUE TITLE
The Site Refused to Render Locally

### ISSUE THREAD

**Issue by network-charles** [weaviate/weaviate-io#2550]
### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

### What part of document/web-page on weaviate.io is affected?

I've been trying to build this website locally to see my modified contribution, however, it's not working. The website was built successfully, but the webpage refused to load. I even had to use a docker image instead, yet it didn't load.

I am hosting the website on a VM on AWS. I can access my exposed nginx container but not the weaviate container. I'd appreciate some feedback on how to resolve this.
The VM specs are:
- 16 GB RAM
- 4 vCPU
- Ubuntu OS

Below is the dockerfile I used.
```dockerfile
FROM node:22.8

WORKDIR /usr/src/app

RUN git clone https://github.com/network-charles/weaviate-io.git

WORKDIR /usr/src/app/weaviate-io

RUN yarn install

EXPOSE 3000

CMD ["yarn", "start", "--host", "0.0.0.0"]
```

```bash
docker build -t weaviate-website:22.8 .

docker run -it -p 3000:3000 weaviate-website:22.8
```

I used the `v22.8` image because I got the below error when I ran `yarn install` with the `v19.9` image.

`error nanoid@5.0.7: The engine "node" is incompatible with this module. Expected version "^18 || >=20". Got "19.9.0"`

**Comment by network-charles** [comment]
The issue has been resolved, I could render the website directly via my host. I'm assuming the issue was from me attempting to use the lower node version `nvm use node 19.9.0`. About the docker script, it's correct, it works.

This error message might be worth looking at `error nanoid@5.0.7: The engine "node" is incompatible with this module. Expected version "^18 || >=20". Got "19.9.0"`.

**Comment by mungitoperrito** [comment]
Closing as resolved per comment
