### ISSUE TITLE
Fixing Issues on the Quickstart Guide

### ISSUE THREAD

**Issue by network-charles** [weaviate/weaviate-io#2552]
### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

### What are the issues you noticed?

The quickstart guide has a few issues. These are as follows:

**An additional unimportant bracket**
> Install the Weaviate [client library](https://weaviate.io/developers/weaviate/client-libraries)) for your preferred programming language.

This should be:
> Install the Weaviate [client library](https://weaviate.io/developers/weaviate/client-libraries) for your preferred programming language.

**Improper use of conjunctions in an unordered list**
> With Weaviate, you have options to:
> - Have Weaviate **create vectors** for you, or
> - Specify **custom vectors**.

This should be:
> With Weaviate, you have two options:
> - Have Weaviate **create vectors** for you
> - Specify **custom vectors**

**Queries for the Python Client v4 is misleading**

The statement "You should see results like this:" is misleading because the query script identifies only one object, and the result identifies two objects.

This mistake excludes the sub-section titled "Generative search (grouped task)".

Also, the `print()` output in the subsection titled "Generative search (single prompt)" is wrong. The output prints only one instance of the object, the instance titled "generated". But the result also includes the "properties" instance. 

**Redundant word and an improper use of commas and a conjunction in an unordered list**

> Well done! You have:
> 
> - Created your own cloud-based vector database with Weaviate,
> - Populated it with data objects using an inference API,
> - Performed searches, including:
>   - Semantic search,
>   - Semantic search with a filter and
>   - Generative search.
> 

Also, the word "own" is redundant in the above.

This should be:

> Well done! You have:
> 
> - Created your cloud-based vector database with Weaviate
> - Populated it with data objects using an inference API
> - Performed searches, including:
>    - Semantic search
>    - Semantic search with a filter
>    - Generative search

### Are you working on this?
Yes

Also, I'd appreciate some feedback if you do not agree with any of the issues I raised.

**Comment by mungitoperrito** [comment]
@network-charles thanks for your suggestions. Do you have a PR open? I didn't see one. 

Most of these suggestions look ok, but it's much easier to work with PRs. Would you open one up?

Thanks!

**Comment by network-charles** [comment]
It’s a pleasure, @mungitoperrito! 

Yes, I’m currently working on the suggestions locally and I will push my commit and open a PR soon.
