### ISSUE TITLE
Missing Port-Forwarding Instructions for Weaviate in Kubernetes (minikube)

### ISSUE THREAD

**Issue by network-charles** [weaviate/weaviate-io#2576]
### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

### What part of document/web-page on weaviate.io is affected?
https://weaviate.io/developers/academy/deployment/k8s/access_weaviate

### Issue
As seen below, by default, in a Kubernetes cluster, Weaviate exposes the container at port `8080` and `50051`.
```yaml
    name: weaviate
    ports:
    - containerPort: 8080
      protocol: TCP
    - containerPort: 50051
      name: grpc
      protocol: TCP
```
Therefore, it expects these container ports to be reachable by default to the host. The current documentation is incomplete about this.

As seen below, the `minikube tunnel` command creates unique **external IP** addresses for each Weaviate service, allowing them to be accessible from the host.

```bash
kubectl get service

NAME                TYPE           CLUSTER-IP       EXTERNAL-IP      PORT(S)           AGE
weaviate            LoadBalancer   10.99.192.19     10.99.192.19     80:32551/TCP      35s
weaviate-grpc       LoadBalancer   10.110.147.194   10.110.147.194   50051:30508/TCP   35s
```

For example, a simple `curl` command to the **external IP** address of the HTTP load balancer service returns a JSON response from the API.

```bash
curl 10.99.192.19

{"links":{"href":"/v1","name":"api v1","documentationHref":"https://weaviate.io/developers/weaviate/current/"}}
```
However, when trying to interact with your pod via a client like the Weaviate Python client for example, the connection fails because the external IP generated for the `weaviate` and `weaviate-grpc` services are unique. So, a user may need to use a **single** unique hostname or IP address to fix this.

### Fix
A quick solution is exposing the service's TCP traffic to the host via **port-forwarding**, so they are accessible via a single domain name like `localhost` or an IP address like `127.0.0.1`.

The documentation currently lacks a command to achieve this. Without it, users may encounter difficulties accessing the pod through a client.

 Additionally, the documentation includes an example that assumes the external IP address is `127.0.0.1` for both services. This may confuse users if there’s no additional configuration specifying that the services need to be exposed to localhost.

### Are you working on this?
Yes, I’ll be opening a PR soon.

**Comment by vidya4499** [comment]
Is this issue still open or you are working on it if its still open i want to work on it

**Comment by network-charles** [comment]
I already opened a PR #2590

**Comment by databyjp** [comment]
Hi @network-charles and thanks for raising this. 

We've consulted our engineers, and they suggested addressing the [topic this way](https://github.com/weaviate/weaviate-io/pull/2709/commits/bc4ad2f04caa02ade7cee9a57e7537fe77745ca8), by explaining how to connect to different sets of IP addresses. 

This will be merged to main towards the end of the week. We really appreciate you bringing this to our attention. :)

**Comment by network-charles** [comment]
It's a pleasure
