### ISSUE TITLE
[Documentation Feedback]: Add words to Glossary

### ISSUE THREAD

**Issue by dandv** [weaviate/weaviate-io#266]
### Page URL

https://weaviate.io/developers/weaviate/current/more-resources/glossary.html

We should decide if this page should explain only Weaviate-specific terms, or general vector search/ML terms. Right now it includes both, e.g. WCS and HNSW.

### Terms to add

* [ ] ANN
* [ ] BERT (also in the image [here](https://weaviate.io/blog/2022/08/Using-Cross-Encoders-as-reranker-in-multistage-vector-search.html))
* [ ] Bi-encoder
* [ ] centroid
* [ ] cosine similarity
* [ ] Cross-encoder
* [ ] dense vector embedding
* [ ] embedding (and what other types exist besides vector embeddings)
* [ ] feature projection
* [ ] loss function
* [ ] pooling (also in the image [here](https://weaviate.io/blog/2022/08/Using-Cross-Encoders-as-reranker-in-multistage-vector-search.html))
* [ ] rank fusion
* [ ] sparse vector
* [ ] vector (emphasized [here](https://weaviate.io/blog/2022/08/Using-Cross-Encoders-as-reranker-in-multistage-vector-search.html))

**Comment by BhaswatiRoy** [comment]
Hello
I would like to work on this issue
Please assign me if it's open

**Comment by databyjp** [comment]
I propose to just focus on Weaviate terms, but I don’t think it would hurt to have additional terms (if they exist already).

I also propose to leave these terms for now, as they are terms of art that can be readily researched. 

Closing this for now.
