### ISSUE TITLE
Improvement suggestion ref2vec

### ISSUE THREAD

**Issue by bobvanluijt** [weaviate/weaviate-io#308]
### Code of Conduct

- [X] I have read and agree to the Weaviate's [Code of Conduct](https://github.com/semi-technologies/weaviate-io/blob/main/CODE_OF_CONDUCT.md)

### What part of document/web-page on weaviate.io is affected?

ref2vec docs

### Additional comments?

Based on feedback from user.

> I do think some bits of documentation are missing or incomplete. I think there could be more documentation on references and the ref2vec component. Some specific examples would be examples of queries (like above). More documentation and examples around using batches and multithreading. And lastly more documentation and examples on querying with the JS library

Link: https://weaviate.slack.com/archives/C017EG2SL3H/p1670279360834049?thread_ts=1669719437.324829&channel=C017EG2SL3H&message_ts=1670279360.834049

**Comment by colemanhindes** [comment]
```
{
  "classes": [
    {
      "class": "Article",
      "description": "A class representing a published article",
      "moduleConfig": {
        "ref2vec-centroid": {
          "referenceProperties": "hasParagraphs",
          "method": "mean"
        }
      },
      "properties": [
        {
          "dataType": [
            "string"
          ],
          "description": "Title of the article",
          "name": "title"
        }
        ,
        {
          "dataType": [
            "Paragraph"
          ],
          "description": "Paragraphs belonging to this article",
          "name": "hasParagraphs"
        }
      ],
      "vectorizer": "ref2vec-centroid"
    },
    {
      "class": "Paragraph",
      "description": "Paragraphs belonging to an Article",
      "properties": [
        {
          "dataType": [
            "text"
          ],
          "description": "Content that will be vectorized",
          "moduleConfig": {
            "text2vec-contextionary": {
              "skip": false,
              "vectorizePropertyName": false
            }
          },
          "name": "content"
        }
      ],
      "vectorizer": "text2vec-contextionary"
    }
  ]
}

```

In this example 
`"referenceProperties": "hasParagraphs",`

should be 
`"referenceProperties": ["hasParagraphs"],`

**Comment by bobvanluijt** [comment]
Thanks @colemanhindes – an array would suggest that you can create centroids based on multiple properties. I assume that it's a string because you take 1 property as input to base centroids on (or am I wrong @CShorten / @parkerduckworth?)

**Comment by colemanhindes** [comment]
Hey @bobvanluijt sorry for the confusion. This was not a suggestion for changing the API/Schema, it was a suggestion for an update to the documentation. When I create a schema structured like the first one it doesn't work and suggests that it needs to be an array. The second one works for me

**Comment by databyjp** [comment]
Looks like this has been addressed; closing the issue.
