### ISSUE TITLE
[Documentation Feedback]: consider a more legible font with the Docusaurus migration

### ISSUE THREAD

**Issue by dandv** [weaviate/weaviate-io#311]
### Page URL

https://weaviate.io/developers/contributor-guide/current/contextionary/classification-benchmarks.html

### User feedback

The currently used font (Alegreya Sans) doesn't make it easy to distinguish between lowercase o and the digit 0, e.g. in the table below. It also uses old-style digits, which look [jarring](https://ux.stackexchange.com/questions/54740/what-is-the-appeal-of-old-style-numbers-and-why-do-modern-fonts-still-include-th).

<img width="121" alt="image" src="https://user-images.githubusercontent.com/33569/206564957-36198794-51f6-417f-9d6a-a7726c64ba95.png">

**Comment by databyjp** [comment]
Hi Dan, do you have a suggested font?

**Comment by dandv** [comment]
GitHub uses this CSS font declaration for normal text:

    -apple-system,BlinkMacSystemFont,"Segoe UI","Noto Sans",Helvetica,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji";

and this one for monospace:

    ui-monospace,SFMono-Regular,SF Mono,Menlo,Consolas,Liberation Mono,monospace

**Comment by databyjp** [comment]
I don't know what the plan is typography-wise but sounds good to me. Thx!

**Comment by databyjp** [comment]
I am closing this for now as we have Docusaurus deployed and some new fonts.
