### ISSUE TITLE
[Documentation Feedback]: grammar mistake

### ISSUE THREAD

**Issue by ayushpattnaik** [weaviate/weaviate-io#378]
## There is a grammatical error in [Unit Tests](https://weaviate.io/developers/contributor-guide/weaviate-core/tests#philosophy) section.

- "the" should be replaced with "to" . 
<img width="818" alt="Screenshot 2023-01-25 at 2 20 12 AM" src="https://user-images.githubusercontent.com/53592579/214409902-7d3cd449-edb8-48b1-9569-a8879eb4e677.png">

**Comment by indrasn0wal** [comment]
Hello, I'm a first-time contributor. Please assign the issue to me.

**Comment by databyjp** [comment]
Thanks @ayushpattnaik ! Merged into main with thanks :)
