### ISSUE TITLE
[Documentation Feedback]: Improving Documentation page needs to be updated

### ISSUE THREAD

**Issue by Asmit2952** [weaviate/weaviate-io#383]
### Page URL

https://weaviate.io/developers/contributor-guide/getting-started/improving-docs

### User feedback

This page was created when weaviate.io was built using Jekyll and hence has the outdated information. The page needs to be updated with current tech stack used so that new contributors can easily contribute to this repository. 

I would like to work on this issue. Cc: @bobvanluijt @sebawita

**Comment by indrasn0wal** [comment]
I'm a first-time contributor. Assign this issue to me

**Comment by indrasn0wal** [comment]
Can you please specify what changes are to be made.

**Comment by databyjp** [comment]
Hi @Asmit2952 - thanks for raising this. I have made updates (#390) to the docs to swap out Jekyll references to Docusaurus references. 

@indrasn0wal and @Asmit2952 - The `Documentation folders` section ([see this page](https://raw.githubusercontent.com/weaviate/weaviate-io/main/developers/contributor-guide/getting-started/improving-docs.md)) still needs updating. If you are looking to contribute please take a look at updating that. 

If you update it, create a PR, and assign me as the reviewer, I will take a look :).

Thanks for your contributions - I will close this particular issue for now. Cheers!
