### ISSUE TITLE
Page not found after clicking on link in faqs

### ISSUE THREAD

**Issue by p-kris10** [weaviate/weaviate-io#414]
### Code of Conduct

- [X] I have read and agree to the Weaviate's [Code of Conduct](https://github.com/weaviate/weaviate-io/blob/main/CODE_OF_CONDUCT.md)

### What part of document/web-page on weaviate.io is affected?

In [developers/weaviate/more-resources)/faq.md](https://github.com/weaviate/weaviate-io/blob/main/developers/weaviate/more-resources/faq.md#q-does-weaviate-use-hnswlib) , 
in the answer to the question "Does Weaviate use Hnswlib?" 
It says "Note I: HNSW is just one implementation in Weaviate, but Weaviate can support multiple indexing algoritmns as outlined [here](https://github.com/weaviate/weaviate-io/blob/main/developers/weaviate/vector-index)"

the "here" points to " https://github.com/weaviate/weaviate-io/blob/main/developers/weaviate/vector-index" which does not exist anymore.

**Comment by YASHpPATIL7** [comment]
I would like to contribute to this issue.
