### ISSUE TITLE
Add docs on how to configure authentication/ OIDC with the helm chart

### ISSUE THREAD

**Issue by samos123** [weaviate/weaviate-io#417]
### Code of Conduct

- [X] I have read and agree to the Weaviate's [Code of Conduct](https://github.com/weaviate/weaviate-io/blob/main/CODE_OF_CONDUCT.md)

### What part of document/web-page on weaviate.io is affected?

https://weaviate.io/developers/weaviate/configuration/authentication

https://weaviate.io/developers/weaviate/installation/kubernetes

Neither of those doc cover how to configure OIDC / Authentication. I wasn't sure how to do it after skipping through the values.yaml file either.

**Comment by databyjp** [comment]
Hi @samos123 - we have added this section. Please let us know if this is sufficient.

https://weaviate.io/developers/weaviate/installation/kubernetes#authentication-and-authorization

**Comment by databyjp** [comment]
Hi @samos123 

We've added this recently:
https://weaviate.io/developers/weaviate/installation/kubernetes#authentication-and-authorization

Does this address the topic sufficiently? Pls let me know if you have any comments :).

JP
