### ISSUE TITLE
react-rangeslider dependency breaks npm install

### ISSUE THREAD

**Issue by dandv** [weaviate/weaviate-io#424]
We use [react-rangeslider](https://www.npmjs.com/package/react-rangeslider) on the [Pricing](https://weaviate.io/pricing) page. That module hasn't been updated since 2017, is [no longer compatible with React](https://github.com/whoisandy/react-rangeslider/issues/176), and [breaks current versions of NPM](https://github.com/whoisandy/react-rangeslider/issues/173). That causes `npm install` to fail after `git clone`ing this repo, which is a friction point for new contributors, forcing them to use yarn.

**Comment by databyjp** [comment]
Closing stale issue.
