### ISSUE TITLE
Unclear OIDC instructions

### ISSUE THREAD

**Issue by dandv** [weaviate/weaviate-io#442]
At https://weaviate.io/developers/weaviate/configuration/authentication#requirements--defaults,

> For very simple use-cases such as for a single user, you can use [Weaviate Cloud Services](https://auth.wcs.api.weaviate.io/) as the OIDC token issuer. Sign up and specify https://auth.wcs.api.weaviate.io/auth/realms/SeMI as the issuer and your sign-up email as the user in the OIDC configuration .

The [Weaviate Cloud Services](https://auth.wcs.api.weaviate.io/) page does not present any way to Sign up:

![image](https://user-images.githubusercontent.com/33569/218449265-dd5e7060-b453-4418-9a93-e531c6c3a419.png)

[Related community Slack thread](https://weaviate.slack.com/archives/C017EG2SL3H/p1673826654201849).

**Comment by dandv** [comment]
CC @databyjp we should improve this as you work on the OIDC blog post.

**Comment by databyjp** [comment]
Hmm okay. I see how it is ambiguous.

I will:
- create a PR for this to clarify between signing up for WCS in general and using WCS as the token issuer. 
- And then close this. 

Cheers!
