### ISSUE TITLE
[Documentation Feedback]: clarify the difference between replicas and nodes

### ISSUE THREAD

**Issue by dandv** [weaviate/weaviate-io#461]
### Page URL

https://weaviate.io/developers/weaviate/concepts/replication-architecture

### User feedback

Would help to clarify,
* nodes
* -> cluster
* replicas
* replica sets

> Sharding handles horizontal scaling across servers by dividing the data and sending the pieces of data (shards) to multiple replica sets
- explain what a replica set is, and what the relationship between the pieces of data is (e.g. how the data is hashed into which shard) 

> For example, you can have 3 replicas of the database and shards set to 3, which means you have 9 shards in total, where each server node holds 3 different shards.
- a clearer example would use different numbers (e.g. 3 replicas and 4 shards). A diagram would help.

> It is possible to split data in Weaviate based on Classes. Note that this is _different from Sharding_
- another type of split?

At https://weaviate.io/developers/weaviate/concepts/replication-architecture/cluster-architecture#write-operations:
> Where something is **replicated** is deterministic, so all nodes know on which **shard** which data will land.

- but [replication is not the same as sharding](https://weaviate.io/developers/weaviate/concepts/replication-architecture#replication-vs-sharding)

**Comment by databyjp** [comment]
Closing as stale
