### ISSUE TITLE
[Documentation Feedback]: add node balancer to leaderless replication diagram

### ISSUE THREAD

**Issue by dandv** [weaviate/weaviate-io#462]
### Page URL

http://localhost:3000/developers/weaviate/concepts/replication-architecture/cluster-architecture#leaderless-design

### User feedback

> There is nothing special about this node, it was chosen to be the coordinator because this node received the request from the load balancer.

It would help to have the load balancer pictured in the diagram.

Also,
* [ ] the diagram legend does not explain the white database nodes (green ones are replicas, the others should be explained - see #463).
* [ ] Under "Replication Factor", `The client sends data to any node, which will be assigned as the coordinator node` - is it the client, or the load balancer who sends data to any node?

**Comment by databyjp** [comment]
Closing as stale
