### ISSUE TITLE
[Documentation Feedback]: Clarify the role of non-replica nodes

### ISSUE THREAD

**Issue by dandv** [weaviate/weaviate-io#463]
### Page URL

http://localhost:3000/developers/weaviate/concepts/replication-architecture/cluster-architecture#replication-factor

### User feedback

> A replication factor of 2 means that there are two copies of each data entry, which are present on two different nodes (replicas). Naturally, the replication factor cannot be higher than the number of nodes.

This begs the question, what do the other nodes do? The question, while seemingly naive, remains unaddressed in the remainder of the page. A brief explanation would help.

**Comment by databyjp** [comment]
Closing as stale
