### ISSUE TITLE
[minor] HTTP request lines are highlighted with the JS highlighter

### ISSUE THREAD

**Issue by dandv** [weaviate/weaviate-io#470]
The problem is visible at https://weaviate.io/developers/weaviate/api/rest/objects

That doesn't quite highlight correctly in Prism. [Example](https://prismjs.com/test.html#language=javascript&text=GET%20%2Fv1%2Fobjects%3Fclass%3D%7BclassName%7D%26limit%3D200%26include%3D%7Binclude%7D):

<img width="625" alt="image" src="https://user-images.githubusercontent.com/33569/220090458-46424ce8-b010-4dd8-9aaa-660a88f2284e.png">

* `class` should be highlighted like `limit`, not like the JS keyword
* `{classname}` and `{include}` should be highlighted like `200`.

See https://github.com/PrismJS/prism/discussions/2936#discussioncomment-5051927

**Comment by databyjp** [comment]
I understand that this is an issue, but I vote to de-priorise this as it is cosmetic, and we are downstream of the cause.

**Comment by databyjp** [comment]
Closing this as a stale issue; largely external factors at play
