### ISSUE TITLE
Remove unused images

### ISSUE THREAD

**Issue by laura-ham** [weaviate/weaviate-io#61]
@bobvanluijt can we remove images that are not used currently? (There are a lot of images still in the repo that were previously used in the Playbook, but that isn't available on weaviate.io right?)

**Comment by bobvanluijt** [comment]
Yes and no. I've been looking into the as well. The problem is this, we don't know which images are _not_ being used so we should write a script to validate this.

**Comment by indrasn0wal** [comment]
Is the issue still open? I would like to contribute to the project

**Comment by bobvanluijt** [comment]
> Is the issue still open? I would like to contribute to the project

If you find any unused images, feel free to help @indrasn0wal 🙏

**Comment by Asmit2952** [comment]
I don't think there are unused images as completely new website has been deployed. This issue was valid when Weaviate's website was in Jekyll. We can close this issue.

**Comment by databyjp** [comment]
Thanks; closing this for now then.
