### ISSUE TITLE
[Documentation Feedback]: Blog hero image appears 5 times in backup tutorial

### ISSUE THREAD

**Issue by dandv** [weaviate/weaviate-io#637]
### Page URL

https://weaviate.io/blog/tutorial-backup-and-restore-in-weaviate#backup-features

### User feedback

Looks like a copy/paste error that maybe replaced a useful image?

**Comment by databyjp** [comment]
Weird. I think maybe a find/replace problem from HRs built with dashes. Fixed with #640. Thanks!
