### ISSUE TITLE
[Documentation Feedback]: Add simpler example for nearText

### ISSUE THREAD

**Issue by dandv** [weaviate/weaviate-io#656]
### Page URL

https://weaviate.io/developers/weaviate/api/graphql/vector-search-parameters#neartext

### User feedback

The two `nearText` examples both use moveTo (from a [concept](https://console.weaviate.io/console/query#weaviate_uri=https://demo.dataset.playground.semi.technology&graphql_query=%7B%0D%0A++Get%7B%0D%0A++++Publication%28%0D%0A++++++nearText%3A+%7B%0D%0A++++++++concepts%3A+%5B%22fashion%22%5D%2C%0D%0A++++++++certainty%3A+0.7%2C%0D%0A++++++++moveAwayFrom%3A+%7B%0D%0A++++++++++concepts%3A+%5B%22finance%22%5D%2C%0D%0A++++++++++force%3A+0.45%0D%0A++++++++%7D%2C%0D%0A++++++++moveTo%3A+%7B%0D%0A++++++++++concepts%3A+%5B%22haute+couture%22%5D%2C%0D%0A++++++++++force%3A+0.85%0D%0A++++++++%7D%0D%0A++++++%7D%0D%0A++++%29%7B%0D%0A++++++name%0D%0A++++++_additional+%7B%0D%0A++++++++certainty%0D%0A++++++%7D%0D%0A++++%7D%0D%0A++%7D%0D%0A%7D) / [object](https://console.weaviate.io/console/query#weaviate_uri=https://demo.dataset.playground.semi.technology&graphql_query=%7B%0D%0A++Get%7B%0D%0A++++Article%28%0D%0A++++++nearText%3A+%7B%0D%0A++++++++concepts%3A+%5B%22traveling+in+Asia%22%5D%2C%0D%0A++++++++certainty%3A+0.7%2C%0D%0A++++++++moveTo%3A+%7B%0D%0A++++++++++objects%3A+%5B%7B%0D%0A++++++++++++%23+this+ID+is+of+the+article%3A%0D%0A++++++++++++%23+%22Tohoku%3A+A+Japan+destination+for+all+seasons.%22%0D%0A++++++++++++id%3A+%222faf2b7d-f185-30c0-8c80-a01b7cfeefb4%22%0D%0A++++++++++%7D%5D%0D%0A++++++++++force%3A+0.85%0D%0A++++++++%7D%0D%0A++++++%7D%0D%0A++++%29%7B%0D%0A++++++title%0D%0A++++++summary%0D%0A++++++_additional+%7B%0D%0A++++++++certainty%0D%0A++++++%7D%0D%0A++++%7D%0D%0A++%7D%0D%0A%7D)), which complicates the GraphQL code for a new reader.

**Comment by databyjp** [comment]
This is a good point - I think it's tackled by the HOWTOs that you are working on, and the references do the job of being a source of a comprehensive set of options. 

So I'm closing this for now.
