### ISSUE TITLE
Weaviate interface and setup to auto-GPT not working

### ISSUE THREAD

**Issue by itsureis** [weaviate/weaviate-io#684]
### Code of Conduct

- [X] I have read and agree to the Weaviate's [Code of Conduct](https://github.com/weaviate/weaviate-io/blob/main/CODE_OF_CONDUCT.md)

### What part of document/web-page on weaviate.io is affected?

https://weaviate.io/blog/autogpt-and-weaviate

### Additional comments?

D:\Alt C drive\AutoGPT\Auto-GPT>docker run -it --env-file=./.env -v $PWD/auto_gpt_workspace:/app/auto_gpt_workspace autogpt
docker: Error response from daemon: create $PWD/auto_gpt_workspace: "$PWD/auto_gpt_workspace" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.

Please update your instructions and confirm sound integration with Auto-GPT via your instructions. I have yet to succeed in integrating weaviate to auto-gpt, even when using a working command:
 docker run -it --env-file=./.env -v D:/Alt_C_drive/AutoGPT/auto_gpt_workspace:/app/auto_gpt_workspace autogpt

**Comment by databyjp** [comment]
Hi there, 

Actually, that Docker command is exactly as suggested by the AutoGPT maintainers, not by us. [Please see this](https://github.com/Significant-Gravitas/Auto-GPT/tree/stable#docker).

It looks like the environment that you're running this is not recognizing `$PWD` as the current working directory. Are you possibly running this from command prompt? If so, that would not work as Cmd does not recognise $PWD as a variable. 

I suggest that you try running it in PowerShell. 

If you're still having trouble, I suggest following the instructions on the AutoGPT GitHub repo (https://github.com/Significant-Gravitas/Auto-GPT/tree/stable) without a vector database set up, and then modifying the `MEMORY_BACKEND` settings to add Weaviate. 

I will close this issue for now as I think it related to AutoGPT set-up. 

If you can get AutoGPT to work but then have issues adding Weaviate as the memory back-end, please feel free to re-open. Thanks!
