### ISSUE TITLE
Outdated Go client path in Quickstart

### ISSUE THREAD

**Issue by unfode** [weaviate/weaviate-io#869]
### Code of Conduct

- [X] I have read and agree to the Weaviate's [Code of Conduct](https://github.com/weaviate/weaviate-io/blob/main/CODE_OF_CONDUCT.md)

### Steps to reproduce the bug

In the [Quickstart guide](https://weaviate.io/developers/weaviate/quickstart#install-a-client-library), the path to the Go client is outdated:

![image](https://github.com/weaviate/weaviate-io/assets/95689995/10097d90-5d31-4535-ab34-db069a7199d5)

When I run the command in terminal, I get:
![image](https://github.com/weaviate/weaviate-io/assets/95689995/d8fe9466-d083-4cd7-8213-f3e5acce1267)

### Expected behavior

Change the path to `github.com/weaviate/weaviate-go-client/v4`

**Comment by databyjp** [comment]
Hi, thanks for pointing this out. I think this is resolved, so will close the issue.
