### ISSUE TITLE
Outdated links in the template for new issues

### ISSUE THREAD

**Issue by unfode** [weaviate/weaviate-io#871]
### Code of Conduct

- [X] I have read and agree to the Weaviate's [Code of Conduct](https://github.com/weaviate/weaviate-io/blob/main/CODE_OF_CONDUCT.md)

### What part of document/web-page on weaviate.io is affected?

Links to the [Contributing guide](https://github.com/weaviate/weaviate-io/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/weaviate/weaviate-io/blob/main/CODE_OF_CONDUCT.md) are dead:

![image](https://github.com/weaviate/weaviate-io/assets/95689995/13fddeed-47ac-4bd9-a138-e1b5684559bd)

**Comment by daveatweaviate** [comment]
Closing - the template has been rewritten
