### ISSUE TITLE
Unresolved type "models" in Quickstart Tutorial in Go

### ISSUE THREAD

**Issue by unfode** [weaviate/weaviate-io#872]
### Code of Conduct

- [X] I have read and agree to the Weaviate's [Code of Conduct](https://github.com/weaviate/weaviate-io/blob/main/CODE_OF_CONDUCT.md)

### What part of document/web-page on weaviate.io is affected?

In the [Quickstart Tutorial](https://weaviate.io/developers/weaviate/quickstart#connect-to-weaviate), I copied and pasted the Go snippet, and found that `models` couldn't be resolved:

![image](https://github.com/weaviate/weaviate-io/assets/95689995/6dd88934-21af-4700-a7ca-a60426f25c8e)

**Comment by databyjp** [comment]
Hi @unfode - I think this has been resolved, by explicitly showing imports for `"github.com/weaviate/weaviate/entities/models"`. Thanks!
