### ISSUE TITLE
Add distance metric schema config example (/config-refs/distances)

### ISSUE THREAD

**Issue by dandv** [weaviate/weaviate-io#910]
### Discussed in https://github.com/weaviate/weaviate-io/discussions/660

<div type='discussions-op-text'>

<sup>Originally posted by **giscus[bot]** April 12, 2023</sup>
# Doc comment on Distance metrics (/config-refs/distances)

- Configuration: Schema

https://weaviate.io/developers/weaviate/config-refs/distances

</div>

**Comment by databyjp** [comment]
Available in https://weaviate.io/developers/weaviate/configuration/schema-configuration#indexing-sharding-and-replication-settings

Will add refactored version down the line
