### ISSUE TITLE
GraphQL's BM25 reranking example is using nearText search

### ISSUE THREAD

**Issue by eostis** [weaviate/weaviate-io#966]
### Code of Conduct

- [X] I have read and agree to the Weaviate's [Code of Conduct](https://github.com/weaviate/weaviate-io/blob/main/CODE_OF_CONDUCT.md)

### What part of document/web-page on weaviate.io is affected?

Documentation: https://weaviate.io/developers/weaviate/search/rerank#reranking-bm25-search-results

The GraphQL example for the BM25 reranking states `nearText: {concepts: "flying"}` instead of `bm25: {query: "flying"}`

**Comment by databyjp** [comment]
Hi @eostis - sorry about that! We've fixed this I believe. Thanks as always :)
